課題③提出
yuta10200831/99-docker-template pull request #3
Opened 2023-07-15 09:52 UTC by yuta10200831

## 作業対象
作業をした教材のURL or 作成したページのURLなどを記載する
[作業をした教材のURL]
https://www.notion.so/9-for-if-bf5e5e2c7af54dc7b590921815bd5d1c
[作成したページ
<img width="1625" alt="スクリーンショット 2023-07-15 18 50 11" src="https://github.com/yuta10200831/99-docker-template/assets/124555669/d2643cf7-c405-4a93-b7d3-725dfc503ea4">
のURL(index.php)]

## 作業詳細
for文で1~9までループするコードを書き、
$iが2の倍数の時は[$iは2の倍数です]と出力し、
$iが3の倍数の時は[$iは3の倍数です]と出力し、
$iが2の倍数かつ3の倍数の時は[$iは2の倍数かつ3の倍数です]
と出力するコードを書きましょう。
(期待する出力)
2は2の倍数です
3は3の倍数です
4は2の倍数です
6は2の倍数かつ3の倍数です
8は2の倍数です
9は3の倍数です
<img width="1735" alt="スクリーンショット 2023-07-15 18 50 15" src="https://github.com/yuta10200831/99-docker-template/assets/124555669/9ec7732a-bede-4c8d-8978-5f9f0f0c0cec">

2023-07-18 02:42 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-18 02:42 UTC, KatsuyaTanaka95 commented on src/public/Q3.php
> +}
for文では、1~9までループするコードにしましょう！！

2023-07-18 13:53 UTC, yuta10200831 commented on src/public/Q3.php
> +}
修正しました！

2023-07-18 13:54 UTC, yuta10200831 commented
1~9までのループへ修正しました。
ご確認宜しくお願い致します！！
<img width="1625" alt="スクリーンショット 2023-07-18 22 52 29" src="https://github.com/yuta10200831/99-docker-template/assets/124555669/99af9f67-a940-419e-ba3b-51b87a3ea656">

2023-07-19 08:46 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
mergeいただけると助かります！🙆🙋😊🌟💫

2023-07-23 06:38 UTC, merged